spring:
  profiles:
    active: custom-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/user_login_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kabbo1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG